services:
  vue-snake-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-snake-game
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
